apiVersion: v1
kind: Pod
metadata:
  name: suse-server
  labels:
    app: suse-server
spec:
  containers:
  - name: suse-server
    image: jdob/susecon-demo:latest
    ports:
    - containerPort: 9977
---
apiVersion: v1
kind: Service
metadata:
  name: suse-server
spec:
  type: LoadBalancer
  ports:
    - port: 8989  # External port
      targetPort: 9977  # Container port
      protocol: TCP
  selector:
    app: suse-server
