name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        run: |
          docker login --username dbw7 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build -t ghcr.io/dbw7/demo-container:latest -f container/Dockerfile container/
          docker push ghcr.io/dbw7/demo-container:latest